### ISSUE TITLE
worker is broken

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/tooltool#11]
Hitting these exceptions:
```
tooltool_api.lib.pulse: Reconnecting in 10 seconds (exception='Traceback (most recent call last):
 File "/appenv/lib/python3.7/site-packages/aioamqp/frame.py", line 78, in read
 data = await reader.readexactly(7)
 File "/usr/local/lib/python3.7/asyncio/streams.py", line 677, in readexactly
 raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 7 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/app/src/tooltool_api/lib/pulse.py", line 107, in create_consumer
 return await _create_consumer(user, password, exchange, topic, callback)
 File "/app/src/tooltool_api/lib/pulse.py", line 46, in _create_consumer
 port=port,
 File "/appenv/lib/python3.7/site-packages/aioamqp/__init__.py", line 63, in connect
 insist=insist)
 File "/appenv/lib/python3.7/site-packages/aioamqp/protocol.py", line 216, in start_connection
 await self.dispatch_frame()
 File "/appenv/lib/python3.7/site-packages/aioamqp/protocol.py", line 263, in dispatch_frame
 frame_channel, frame = await self.get_frame()
 File "/appenv/lib/python3.7/site-packages/aioamqp/protocol.py", line 250, in get_frame
 return await amqp_frame.read(self._stream_reader)
 File "/appenv/lib/python3.7/site-packages/aioamqp/frame.py", line 80, in read
 raise exceptions.AmqpClosedConnection() from ex
aioamqp.exceptions.AmqpClosedConnection')
```

Also have `aioamqp.protocol: only PLAIN login_method is supported, falling back to AMQPLAIN` in the logs.

**Comment by mozbhearsum** [comment]
As best I can tell, this started with the deploy on November 11th, and the only code change that I see is https://github.com/mozilla-releng/tooltool/commit/da1e386fd0e88217a2a564e0275adc218a6a4fb3, 
which doesn't look remotely related.

I also looked in the cloudops repo, and the only notable thing was a change on Nov 7th that added some config variables (https://github.com/mozilla-services/cloudops-infra/commit/3ee99e07ffd0dfcb183cab4f813c18ea4ecbd40d#diff-47e2aa3945d7ca442e2be075b2d60730, for those that have access). However, there was a deploy on Nov 9th that didn't have this issue, so that seems unlikely to be related.

@oremj - is it possible to tell me if any secrets or other config not in `cloudops-infra` changed between the deploys on Nov 9th and Nov 11th?

My other theory, which seems less likely now, is that it was caused by one of the packages we took when `tooltool` migrated out of services. Most notably:
* `aioamqp` 0.12.0 -> 0.14.0
* `amqp` 2.4.2 -> 2.5.2

...however, I would've expected to start seeing errors earlier than November 11th if this was the cause.

**Comment by oremj** [comment]
There was a tooltool secret change on November 11th via a request from @garbas on slack.

**Comment by sciurus** [comment]
This surfaces on the rabbitmq side in logs like


```
=ERROR REPORT==== 11-Dec-2019::22:03:25 ===
closing AMQP connection <0.4867.4015> (35.233.150.32:40258 -> 10.51.2.39:5671):
{handshake_error,starting,0,
                 {amqp_error,access_refused,
                             "PLAIN login refused: user 'releng-tooltool-staging' - invalid credentials",
                             'connection.start_ok'}}
```

**Comment by mozbhearsum** [comment]
> This surfaces on the rabbitmq side in logs like
> 
> ```
> =ERROR REPORT==== 11-Dec-2019::22:03:25 ===
> closing AMQP connection <0.4867.4015> (35.233.150.32:40258 -> 10.51.2.39:5671):
> {handshake_error,starting,0,
>                  {amqp_error,access_refused,
>                              "PLAIN login refused: user 'releng-tooltool-staging' - invalid credentials",
>                              'connection.start_ok'}}
> ```

Thank you, that's very helpful! So...I guess we need to find the right credentials then, heh.

**Comment by mozbhearsum** [comment]
We fixed the credentials issue but we're still seeing the original traceback on the client. @sciurus has confirmed that we're no longer seeing credential issues on the server, and I do see successful logins on the client as well. So, there's a secondary issue to look into on the client, too.

**Comment by rail** [comment]
Sentry looks quiet too \o/

**Comment by mozbhearsum** [comment]
And now that I'm looking a few hours later, there's no more errors on the client. I'm guessing the ones that I saw shortly after the deployment were the old pod before it shut down. Calling this fixed. Thanks folks!
