### ISSUE TITLE
Update documentation on credentials.

### ISSUE THREAD

**Issue by tomprince** [mozilla-releng/tooltool#15]
I'm looking at https://docs.mozilla-releng.net/projects/tooltool.html#request-authentication-credentials-for-the-client-tooltool-py (which I don't know where is now maintained, if anywhere).

The instructions say that people should file a bug, and then we will generate taskcluster credentials for them.

This should be changed to indicate that we will grant their taskcluster role the appropriate scopes, and then they can create a client with the appropriate scopes to use tooltool. 

It may also make sense to tooltool to use the standard taskcluster environment variables, rather than having its own file format for them.

**Comment by tomprince** [comment]
Per [Bug 1605448](https://bugzilla.mozilla.org/show_bug.cgi?id=1605448), we will be using two LDAP groups to control access.

**Comment by escapewindow** [comment]
appears to be from https://github.com/mozilla/release-services/blob/8ccf9b6a0818d82c8dd917b05aea4e575cbef61b/src/docs/projects/tooltool.rst , which is archived. i wonder if we should find what's hosting that page and turn it off

**Comment by mozbhearsum** [comment]
> appears to be from https://github.com/mozilla/release-services/blob/8ccf9b6a0818d82c8dd917b05aea4e575cbef61b/src/docs/projects/tooltool.rst , which is archived. i wonder if we should find what's hosting that page and turn it off

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1643119 for this. We can track updating the real docs here.

**Comment by mozbhearsum** [comment]
I updated the docs in this repo. The ones in mozrelengdocs don't exist anymore. We'll probably update them at some point - but that's a more overarching issue than this issue is tracking IMO.
